version: '3.8'
services:
  workwise_bff:
    container_name: application
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    restart: always
    ports:
      - "4000:4000"
    environment:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1